root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
systemd-timesync:x:101:102:systemd Time Synchronization,,,:/run/systemd:/usr/sbin/nologin
systemd-network:x:102:103:systemd Network Management,,,:/run/systemd:/usr/sbin/nologin
systemd-resolve:x:103:104:systemd Resolver,,,:/run/systemd:/usr/sbin/nologin
mysql:x:104:110:MySQL Server,,,:/nonexistent:/bin/false
ntp:x:105:111::/nonexistent:/usr/sbin/nologin
messagebus:x:106:112::/nonexistent:/usr/sbin/nologin
arpwatch:x:107:114:ARP Watcher,,,:/var/lib/arpwatch:/bin/sh
Debian-exim:x:108:115::/var/spool/exim4:/usr/sbin/nologin
uuidd:x:109:116::/run/uuidd:/usr/sbin/nologin
redsocks:x:110:117::/var/run/redsocks:/usr/sbin/nologin
tss:x:111:118:TPM2 software stack,,,:/var/lib/tpm:/bin/false
rwhod:x:112:65534::/var/spool/rwho:/usr/sbin/nologin
iodine:x:113:65534::/var/run/iodine:/usr/sbin/nologin
stunnel4:x:114:121::/var/run/stunnel4:/usr/sbin/nologin
miredo:x:115:65534::/var/run/miredo:/usr/sbin/nologin
dnsmasq:x:116:65534:dnsmasq,,,:/var/lib/misc:/usr/sbin/nologin
sslh:x:117:123::/nonexistent:/usr/sbin/nologin
postgres:x:118:125:PostgreSQL administrator,,,:/var/lib/postgresql:/bin/bash
usbmux:x:119:46:usbmux daemon,,,:/var/lib/usbmux:/usr/sbin/nologin
rtkit:x:120:127:RealtimeKit,,,:/proc:/usr/sbin/nologin
_rpc:x:121:65534::/run/rpcbind:/usr/sbin/nologin
Debian-snmp:x:122:129::/var/lib/snmp:/bin/false
statd:x:123:65534::/var/lib/nfs:/usr/sbin/nologin
inetsim:x:124:130::/var/lib/inetsim:/usr/sbin/nologin
sshd:x:125:65534::/run/sshd:/usr/sbin/nologin
pulse:x:126:132:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin
speech-dispatcher:x:127:29:Speech Dispatcher,,,:/var/run/speech-dispatcher:/bin/false
avahi:x:128:135:Avahi mDNS daemon,,,:/var/run/avahi-daemon:/usr/sbin/nologin
saned:x:129:136::/var/lib/saned:/usr/sbin/nologin
colord:x:130:138:colord colour management daemon,,,:/var/lib/colord:/usr/sbin/nologin
geoclue:x:131:139::/var/lib/geoclue:/usr/sbin/nologin
king-phisher:x:132:140::/var/lib/king-phisher:/usr/sbin/nologin
Debian-gdm:x:133:141:Gnome Display Manager:/var/lib/gdm3:/bin/false
dradis:x:134:142::/var/lib/dradis:/usr/sbin/nologin
beef-xss:x:135:143::/var/lib/beef-xss:/usr/sbin/nologin
systemd-coredump:x:999:999:systemd Core Dumper:/:/usr/sbin/nologin
nvpd:x:136:144:NVIDIA Persistence Daemon,,,:/var/run/nvpd/:/usr/sbin/nologin
